title: Two-Jay의 블로그
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://two-jay.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jeong-Jun Kim # add your name
author-img: jekim.png # add your photo
about-author: ML/AI Engineering, Pythonist. Always learning for growth # add description
social-github: Two-Jay # add your Github handle
social-linkedin: two-jay # add your Linkedin handle
social-email: djeeee1272@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-github-chart
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
